/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package formularios;

import base_datos.Detalles_prestamoDao;
import base_datos.LibroDao;
import base_datos.PrestamoDao;
import clases.Detalles_prestamo;
import clases.Libro;
import clases.Prestamo;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andre
 */
public class frmDetalles_Prestamo extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmDetalles_Prestamo
     */
    public frmDetalles_Prestamo() {
        initComponents();
        generar_CB_libro();
        generar_CB_prestamo();
        llenar_tabla();
    }
    
    private void generar_CB_libro(){
        cbLibro.removeAllItems();
        
        ArrayList<Libro> arreglo_libros = new ArrayList<Libro>();
        LibroDao librodao= new LibroDao();
        librodao.consultar_LibroCB();
        arreglo_libros = librodao.consultar_LibroCB();
        Iterator<Libro> iterator_libro = arreglo_libros.iterator();
        
        while(iterator_libro.hasNext()){
            Libro objeto_libro = iterator_libro.next();
            cbLibro.addItem(objeto_libro);
        } 
    }
    
    private void generar_CB_prestamo(){
        cbPrestamo.removeAllItems();
        
        ArrayList<Prestamo> arreglo_prestamos = new ArrayList<Prestamo>();
        PrestamoDao prestamodao = new PrestamoDao();
        prestamodao.consultar_PrestamoCB();
        arreglo_prestamos = prestamodao.consultar_PrestamoCB();
        Iterator<Prestamo> iterator_prestamo = arreglo_prestamos.iterator();
        
        while(iterator_prestamo.hasNext()){
            Prestamo objeto_prestamo = iterator_prestamo.next();
            cbPrestamo.addItem(objeto_prestamo);
        } 
    }
    
    private void limpiar_tabla(){
        DefaultTableModel modeloTabla = (DefaultTableModel) jtbDetalles.getModel();
        int total_registro = jtbDetalles.getRowCount() - 1;
        for(int i = total_registro; i >= 0; i--){
            //modeloTabla.removeRow(modeloTabla.getRowCount() - 1); 
            modeloTabla.removeRow(i); 
        }          
    }
    
    private void llenar_tabla(){
        DefaultTableModel modeloTabla;
        modeloTabla = (DefaultTableModel)jtbDetalles.getModel();
        ArrayList<Detalles_prestamo> arreglo_Detalles = new ArrayList<Detalles_prestamo>();
        Detalles_prestamoDao detallesdao = new Detalles_prestamoDao();
        
        arreglo_Detalles = detallesdao.consultar_prestamo();
        Object[] obj_Detalles = new Object[3];        
        Iterator<Detalles_prestamo> iterator_detalles = arreglo_Detalles.iterator();
        
        while(iterator_detalles.hasNext()){ //hasnext para saber si tiene valor, es decir, mientras tenga valores siga en el ciclo.
            Detalles_prestamo objeto_prestamo = iterator_detalles.next();
            obj_Detalles[0] = objeto_prestamo.getId_libro();
            obj_Detalles[1] = objeto_prestamo.getId_prestamo();
            obj_Detalles[2] = objeto_prestamo.getFecha_devolucion();
            
            
            modeloTabla.addRow(obj_Detalles);
        }
        
        jtbDetalles.setModel(modeloTabla);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbLibro = new javax.swing.JComboBox<>();
        cbPrestamo = new javax.swing.JComboBox<>();
        txtFechaDev = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbDetalles = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("DETALLES DEL PRESTAMO");

        jLabel2.setText("Id Libro");

        jLabel3.setText("Id Prestamo");

        jLabel4.setText("Fecha Devolucion (dd/MM/yyyy)");

        cbLibro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLibroActionPerformed(evt);
            }
        });

        cbPrestamo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPrestamoActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jtbDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Libro", "Id Prestamo", "Fecha Devolucion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtbDetalles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbDetallesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbDetalles);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaDev, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFechaDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try{
            String strFechaDevolucion = txtFechaDev.getText();
            Date datFechaDevolucion = null;
            
            Libro libro = new Libro();
            libro = (Libro) cbLibro.getSelectedItem();
            
            System.out.println("El nombre del libro seleccionado es: " + libro.getNombre());
            System.out.println("El id del libro seleccionado es: " + libro.getId_libro());
            
            Prestamo prestamo = new Prestamo();
            prestamo = (Prestamo) cbPrestamo.getSelectedItem();
            
            System.out.println("El id del prestamo es: " + prestamo.getId_prestamo());
            System.out.println("El id del socio que hizo este prestamo es: " + prestamo.getId_socio()); 
            
            try{
                datFechaDevolucion = new SimpleDateFormat("dd/MM/yyyy").parse(strFechaDevolucion);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, "Error al convertir fecha " + e, "Error", JOptionPane.ERROR_MESSAGE);
            }

            Detalles_prestamo detalles_prestamo = new Detalles_prestamo(libro.getId_libro(), prestamo.getId_prestamo() , datFechaDevolucion);
            
            Detalles_prestamoDao detalles_prestamodao = new Detalles_prestamoDao();
            boolean bolGuardoDatos = false;
            bolGuardoDatos = detalles_prestamodao.guardar_detallesPR(detalles_prestamo);

            if(!bolGuardoDatos){
                limpiar_tabla();
                JOptionPane.showMessageDialog(this, "Ingreso los datos correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                llenar_tabla();
            }
            else{
                JOptionPane.showMessageDialog(this, "NO Ingreso los datos correctamente", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error al ingresar datooos " + e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cbLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLibroActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbLibroActionPerformed

    private void cbPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPrestamoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbPrestamoActionPerformed

    private void jtbDetallesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbDetallesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbDetallesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<Object> cbLibro;
    private javax.swing.JComboBox<Object> cbPrestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtbDetalles;
    private javax.swing.JTextField txtFechaDev;
    // End of variables declaration//GEN-END:variables
}
