/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

/**
 *
 * @author andre
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdFormularios = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmLibros = new javax.swing.JMenuItem();
        jmAutor = new javax.swing.JMenuItem();
        jmSocio = new javax.swing.JMenuItem();
        jmPrestamo = new javax.swing.JMenuItem();
        jmDetalles_Prestamos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdFormulariosLayout = new javax.swing.GroupLayout(jdFormularios);
        jdFormularios.setLayout(jdFormulariosLayout);
        jdFormulariosLayout.setHorizontalGroup(
            jdFormulariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );
        jdFormulariosLayout.setVerticalGroup(
            jdFormulariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        jMenu1.setText("Biblioteca");

        jmLibros.setText("Libros");
        jmLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmLibrosActionPerformed(evt);
            }
        });
        jMenu1.add(jmLibros);

        jmAutor.setText("Autores");
        jmAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAutorActionPerformed(evt);
            }
        });
        jMenu1.add(jmAutor);

        jmSocio.setText("Socios");
        jmSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSocioActionPerformed(evt);
            }
        });
        jMenu1.add(jmSocio);

        jmPrestamo.setText("Prestamos");
        jmPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPrestamoActionPerformed(evt);
            }
        });
        jMenu1.add(jmPrestamo);

        jmDetalles_Prestamos.setText("Detalles Prestamos");
        jmDetalles_Prestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDetalles_PrestamosActionPerformed(evt);
            }
        });
        jMenu1.add(jmDetalles_Prestamos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdFormularios)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdFormularios, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmLibrosActionPerformed
        // TODO add your handling code here:
        frmLibro libros = new frmLibro();
        jdFormularios.add(libros);
        libros.setVisible(true);
    }//GEN-LAST:event_jmLibrosActionPerformed

    private void jmAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAutorActionPerformed
        // TODO add your handling code here:
        frmAutor autor = new frmAutor();
        jdFormularios.add(autor);
        autor.setVisible(true);        
    }//GEN-LAST:event_jmAutorActionPerformed

    private void jmSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSocioActionPerformed
        // TODO add your handling code here:
        frmSocio socio = new frmSocio();
        jdFormularios.add(socio);
        socio.setVisible(true);  
    }//GEN-LAST:event_jmSocioActionPerformed

    private void jmPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPrestamoActionPerformed
        // TODO add your handling code here:
        frmPrestamo prestamo = new frmPrestamo();
        jdFormularios.add(prestamo);
        prestamo.setVisible(true);  
    }//GEN-LAST:event_jmPrestamoActionPerformed

    private void jmDetalles_PrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDetalles_PrestamosActionPerformed
        // TODO add your handling code here:
        frmDetalles_Prestamo detalles_prestamo = new frmDetalles_Prestamo();
        jdFormularios.add(detalles_prestamo);
        detalles_prestamo.setVisible(true);
    }//GEN-LAST:event_jmDetalles_PrestamosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdFormularios;
    private javax.swing.JMenuItem jmAutor;
    private javax.swing.JMenuItem jmDetalles_Prestamos;
    private javax.swing.JMenuItem jmLibros;
    private javax.swing.JMenuItem jmPrestamo;
    private javax.swing.JMenuItem jmSocio;
    // End of variables declaration//GEN-END:variables
}
