/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package formularios;

import base_datos.PrestamoDao;
import clases.Socio;
import java.util.ArrayList;
import base_datos.SocioDao;
import clases.Prestamo;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andre
 */
public class frmPrestamo extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmPrestamo
     */
    public frmPrestamo() {
        initComponents();
        generar_CB_socio();
        llenar_tabla();
    }
    
    private void generar_CB_socio(){
        cbSocio.removeAllItems();
        
        ArrayList<Socio> arreglo_socios = new ArrayList<Socio>();
        SocioDao sociodao= new SocioDao();
        sociodao.consultar_SocioCB();
        arreglo_socios = sociodao.consultar_SocioCB();
        Iterator<Socio> iterator_socio = arreglo_socios.iterator();
        
        while(iterator_socio.hasNext()){
            Socio objeto_socio = iterator_socio.next();
            cbSocio.addItem(objeto_socio);
        } 
    }
    
    private void limpiar_tabla(){
        DefaultTableModel modeloTabla = (DefaultTableModel) jtbSocio.getModel();
        int total_registro = jtbSocio.getRowCount() - 1;
        for(int i = total_registro; i >= 0; i--){
            //modeloTabla.removeRow(modeloTabla.getRowCount() - 1); 
            modeloTabla.removeRow(i); 
        }          
    }
    
    private void llenar_tabla(){
        DefaultTableModel modeloTabla;
        modeloTabla = (DefaultTableModel)jtbSocio.getModel();
        ArrayList<Prestamo> arreglo_prestamo = new ArrayList<Prestamo>();
        PrestamoDao prestamodao = new PrestamoDao();
        
        arreglo_prestamo = prestamodao.consultar_prestamo();
        Object[] obj_prestamo = new Object[4];        
        Iterator<Prestamo> iterator_autor = arreglo_prestamo.iterator();
        
        while(iterator_autor.hasNext()){ //hasnext para saber si tiene valor, es decir, mientras tenga valores siga en el ciclo.
            Prestamo objeto_prestamo = iterator_autor.next();
            obj_prestamo[0] = objeto_prestamo.getId_prestamo();
            obj_prestamo[1] = objeto_prestamo.getFecha_entrega();
            obj_prestamo[2] = objeto_prestamo.getId_socio();
            obj_prestamo[3] = objeto_prestamo.getCantidad_libros();
            
            modeloTabla.addRow(obj_prestamo);
        }
        
        jtbSocio.setModel(modeloTabla);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFechaEntrega = new javax.swing.JTextField();
        txtCantLibros = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        cbSocio = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbSocio = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("PRESTAMOS");

        jLabel3.setText("Fecha Prestamo (dd/MM/yyyy)");

        jLabel4.setText("Socio");

        jLabel5.setText("Cantidad de Libros");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        cbSocio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jtbSocio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Prestamo", "Fecha entrega", "Id Socio", "Cant. Libros"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtbSocio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbSocioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbSocio);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFechaEntrega)
                            .addComponent(txtCantLibros)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(cbSocio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(47, 47, 47))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCantLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try{
            String strCantLibros = txtCantLibros.getText();
            int intCantLibros = Integer.parseInt(strCantLibros);
            String strFechaEntrega = txtFechaEntrega.getText();
            Date datFechaEntrega = null;
            
            Socio socio = new Socio();
            socio = (Socio) cbSocio.getSelectedItem();
            
            System.out.println("El nombre del socio seleccionado es: " + socio.getNombre());
            System.out.println("El id del socio seleccionado es: " + socio.getId_socio());
            
            
            
            try{
                datFechaEntrega = new SimpleDateFormat("dd/MM/yyyy").parse(strFechaEntrega);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, "Error al convertir fecha " + e, "Error", JOptionPane.ERROR_MESSAGE);
            }

            Prestamo prestamo = new Prestamo(datFechaEntrega, socio.getId_socio(), intCantLibros);
            
            PrestamoDao prestamodao = new PrestamoDao();
            boolean bolGuardoDatos = false;
            bolGuardoDatos = prestamodao.guardar_prestamo(prestamo);

            if(!bolGuardoDatos){
                limpiar_tabla();
                JOptionPane.showMessageDialog(this, "Ingreso los datos correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                llenar_tabla();
            }
            else{
                JOptionPane.showMessageDialog(this, "NO Ingreso los datos correctamente", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error al ingresar datooos " + e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jtbSocioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbSocioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbSocioMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<Object > cbSocio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtbSocio;
    private javax.swing.JTextField txtCantLibros;
    private javax.swing.JTextField txtFechaEntrega;
    // End of variables declaration//GEN-END:variables
}
